### ISSUE TITLE
Tracking issue for Build

### ISSUE THREAD

**Issue by person-m** [raven-os/build-raven-os-org#1]
The main goal of this website will be to add manifest, build them with [nest-build](https://github.com/raven-os/nbuild) and thanks to that, create new packages.

- [ ] Add a manifest
  - [ ] File upload on nest-server
  - [ ] Online editor
- [ ] List manifests already upload. Each manifest will be stocked on nest-server, we can browse them with a filesystem
- [ ] Add a manifest in queue and if it's possible, build it with nest-build
- [ ] List all manifests on the waiting list or already built with a little color
- [ ] Stock in database some informations (parameter used to build, status, logs)
- [ ] Print logs for a given build with a specific view
- [ ] Button to rebuild a manifest that failed
