### ISSUE TITLE
Tracking issues for API

### ISSUE THREAD

**Issue by BourgoisMickael** [raven-os/build-raven-os-org#4]
- [x] Endpoint POST manifest (see #5)
- [x] Endpoint PUT manifest (see #6)
- [x] Change database management system for postgreSQL (see #7)
- [x] Implement a queue system (see #8)
- [x] Implement a worker (see #9)
- [x] Endpoint to handle builds and queue (see #10 & #11)
